version: '2'
services:
  pgcopy:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: bash -c "while ! nc -z pgsql 5432; do sleep 1; done; pip3 freeze; python3 -m pytest tests/"
    container_name: pgcopy
    environment:
      - POSTGRES_DB=pgcopy_test
      - POSTGRES_HOST=pgsql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - pgsql

  pgsql:
    image: postgres:12
    environment:
      - POSTGRES_DB=pgcopy_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
